language: python
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6
    - python: 3.5

install:
 - pip install -U pip
 - pip install -U flake8
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -U black; fi
 - pip install -U -r requirements.txt

script:
 # Static analysis
 - flake8 --statistics --count
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --diff .; fi

 # Test run
 - python everyfinnishno.py --help
 - python everyfinnishno.py --yaml everyfinnishno_example.yaml --test
